const skills = {
  current: [
    'TypeScript',
    'JavaScript (ES6)',
    'React',
    'Next.js',
    'Node.js',
    'HTML5',
    'CSS3',
    'Tailwind CSS',
    'Sequelize',
    'Express.js',
    'MySQL',
    'MongoDB',
    'Mongoose',
    'GraphQL',
    'REST APIs',
    'Bootstrap',
    'Sanity.io CMS',
    'SCSS',
    'Jest',
    'MVC Architecture ',
    'TDD & Agile Methodologies',
    'Heroku',
    'Netlify',
    'MongoDB Atlas',
    'OOP',
    'Handlebars',
    'Webpack Bundler',
    'Babel',
  ],

  previous: ['Python', 'Kotlin'],
}

export default skills
